### ISSUE TITLE
Kuboard.yaml 下载不了

### ISSUE THREAD

**Issue by yanghao19890607** [shaohq/kuboard-issues#3]
https://raw.githubusercontent.com/eip-work/eip-monitor-repository/master/dashboard/Kuboard.yaml 

404了 大佬

**Comment by shaohq** [comment]
是文档中写错了，正确链接是 https://raw.githubusercontent.com/eip-work/eip-monitor-repository/master/dashboard/kuboard.yaml
已修复此问题。
